apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: device-management
  name: device-management
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: device-management
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: device-management
    spec:
      containers:
        - env:
            - name: DATABASE_URI
              value: postgresql://username:password@db/db_devices
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq/
          image: device-management
          name: device-management
          ports:
            - containerPort: 5001
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: device-management-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: device-management-cm0
          name: device-management-cm0
