version: '3.8'
services:
  signing-service:
    build: .
    container_name: signing-service
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET_KEY=1234
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db_auth
    ports:
      - "5432:5432"